In [1]:
import pandas as pd
import numpy as np
import spacy
from textblob import TextBlob
from sklearn.metrics import classification_report

In [2]:
# url='https://drive.google.com/file/d/1_nbSPqf4a3x2gH38syU75gFh5JXojY6B/view?usp=sharing'
# url2='https://drive.google.com/uc?id=' + url.split('/')[-2]
# url2

In [3]:
data = pd.read_csv('https://drive.google.com/uc?id=1_nbSPqf4a3x2gH38syU75gFh5JXojY6B',nrows=1000)
data.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
data['TextBlob_Subjectivity'] = data['review'].apply(lambda x: TextBlob(x).sentiment.subjectivity)
data['TextBlob_Polarity'] = data['review'].apply(lambda x: TextBlob(x).sentiment.polarity)
# Subjectivity score:(More Objective) 0 ------- 1 (More Subjective)
# Polarity score: Sentiment score between (Negative)-1 ------  +1 (Positive)

In [6]:
data['TextBlob_Analysis'] = data['TextBlob_Polarity'].apply(lambda x: 'negative' if x<0 else 'positive')

In [8]:
data

,review,sentiment,TextBlob_Subjectivity,TextBlob_Polarity,TextBlob_Analysis
0,One of the other reviewers has mentioned that ...,positive,0.490369,0.023433,positive
1,A wonderful little production. <br /><br />The...,positive,0.559343,0.109722,positive
2,I thought this was a wonderful way to spend ti...,positive,0.658730,0.354008,positive
3,Basically there's a family where a little boy ...,negative,0.454167,-0.057813,negative
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,0.452916,0.217952,positive
...,...,...,...,...,...
995,Nothing is sacred. Just ask Ernie Fosselius. T...,positive,0.553143,0.158892,positive
996,I hated it. I hate self-aware pretentious inan...,negative,0.509615,-0.370513,negative
997,I usually try to be professional and construct...,negative,0.533213,-0.161574,negative
998,If you like me is going to see this in a film ...,negative,0.612681,-0.051087,negative
999,"This is like a zoology textbook, given that it...",negative,0.461249,0.087956,positive

In [9]:
print(classification_report(data['sentiment'], data['TextBlob_Analysis']))

              precision    recall  f1-score   support

    negative       0.88      0.46      0.60       499
    positive       0.64      0.94      0.76       501

    accuracy                           0.70      1000
   macro avg       0.76      0.70      0.68      1000
weighted avg       0.76      0.70      0.68      1000